### PR TITLE
Deploying the new website

### LINKED ISSUE #2: Updated project homepage
Update the [landing page](http://microbiome.github.io/). 

There has been good feedback from [distill](https://rstudio.github.io/distill/). That could provide the basis.

### PR DESCRIPTION
**Pull request by ake123**
Deploying the new website

### CODE REVIEW

**Comment by TuomasBorman** [comment]
https://akejeb.github.io/miaverse/


@antagomir

**Review by TuomasBorman — APPROVED** [review]

**Comment by antagomir** [comment]
Looks very nice, and I think it could be published.

At the same time I think that probably much of that information should be in OMA directly? The website can be useful for advertising the project in complementary ways but it must not replicate OMA content.  Hence I suggest to see what could be moved in OMA instead so that those resources can easily be found from there. 

We can aim to clarify the exact purpose of the landing page will be, compared to OMA.

**Comment by TuomasBorman** [comment]
So the new page should more or less replicate the information that is on the old page https://microbiome.github.io/?

**Comment by antagomir** [comment]
Yes, for now. That's why I think it is good to publish since it is already there and Jeba's version looks much nicer.

Yet, after this it would make sense move some of that material to OMA and clarify the purpose of the website. I am not sure if the purpose is clear with the current page, either. Or we can abandon the landing page but I think it could be useful as a more general project landing page, for instance if there will be later resources that fall outside of OMA scope etc.

**Comment by TuomasBorman** [comment]
True, I will merge this and create issue

**Comment by ake123** [comment]
Yes, maybe we can remove the Data and Data container section

**Pull request merged**
