### PR TITLE
re-organise homepage

### PR DESCRIPTION
**Pull request by 0xMuluh**
ping #5 @TuomasBorman 
- Restructure homepage
- push relevant sections to menu accessibility
- remove logos
- add clients to footer

### CODE REVIEW

**Comment by TuomasBorman** [comment]
https://github.com/microbiome/OMA/issues/247

**Review by TuomasBorman — CHANGES_REQUESTED** [review]
Now the text seem to be moved to header. Also the structure is broken

The website should have all the old information so that user can find them. However, instead of writing the information to website you should use links.

For instance:

"The miaverse is R/Bioconductor (link to Bioconductor) framework for microbiome data science. In addition to methods, it includes comprehensive online book OMA (link to OMA) The miaverse is expanding ... . You can  find more information from here (link to oma miaverse indroduction)."

"We arrange trainimg.. miaverse has been in several events. You can find more information on training from OMA (link)."

 "miaverse is collaborarive, open-source framework. See the full contributor list from OMA. See how to contribute.."
 
--> So user should find all the old information easily from the new page also. However, they should be behind links. That way you can shorten the page a lot.

**Comment by TuomasBorman** [comment]
You have to remember that this is the first thing that user sees (this landing page is in stickers).

1. User should get excited that mia is THE methods for microbiome data science (Bioconductor is big part)
2. User should find easily the information from where to continue exploring this

**Comment by 0xMuluh** [comment]
Good to check now

**Comment by TuomasBorman** [comment]
I think it can still be much shorter. There are duplicated information (info can be found from OMA)

I think the first part in here https://microbiome.github.io/ ("miaverse:" and the text below) is good.

So something like this


miaverse:

R/Bioconductor framework for microbiome data science. We are envisioning to rethink microbiome data science in R/Bioconductor. This is an open source project developing R/Bioc methods, benchmarking data, and educational material for microbiome research based on the SummarizedExperiment class and its derivatives. New contributions are very welcome.


Resources (similar icons and list as currently)

- mia: Data analysis
- miaViz: Visualization
- miaSim: Simulation
- miaTime: Time series analysis
- Other packages: The package ecosystem is supported by many independent developers (link to here https://microbiome.github.io/OMA/docs/devel/pages/06_packages.html#ecosystem)
- Orchestrating Microbiome Analysis with Bioconductor (OMA): Online book
- Outreach: Slides, posters, and other material (link to here https://github.com/microbiome/outreach)
- Presentations: Link to here https://microbiome.github.io/outreach/

Developers

The full list of contributors varies over time, and is identified through the individual repositories. Check each individual package for acknowledgements, contact information and references. Don't hesitate to contact us for feedback, support, feature requests, or if you want to contribute.

Visit [here](https://microbiome.github.io/OMA/docs/devel/pages/90_acknowledgments.html) for information about the miaverse team and how to join us!

**Comment by TuomasBorman** [comment]
Looks very nice!

Can you still:

1.

I think the search bar is not necessary. The old version did not have that.

2.
miavers title is different from the old one. I think the old one was better. That way it is not listed in the header. --> it is the title of the page. Also the style is little bit different (the old one was better).

See the old page: https://microbiome.github.io/

3.

Can you still add "Presentations" to Resources list? You can use the same icon as in old page. Add link to here: https://microbiome.github.io/outreach/

4.

It is important to add Bioconductor logo. You can add it to same place where we have R, Research council of Finland... (Use the original logo, not the sticker one)

**Comment by TuomasBorman** [comment]
The full list of contributors varies over time, and is identified through the individual repositories. Check each individual package for acknowledgements, contact information and references. Don't hesitate to contact us for feedback, support, feature requests, or if you want to contribute. Visit [here](https://microbiome.github.io/OMA/docs/devel/pages/98_exercises.html) for information about the miaverse team and how to join us!

Remove the line break. It looks better without it.

ALSO: the link is incorrect. It should link to acknowledgements: https://microbiome.github.io/OMA/docs/devel/pages/90_acknowledgments.html

**Comment by TuomasBorman** [comment]
Github link should be to here: https://github.com/microbiome

E:

Also we do not have Mastodon. So you could comment out that icon

**Comment by 0xMuluh** [comment]
Great. I have updated the homepage.

**Comment by TuomasBorman** [comment]
One last request:

In the old page, the logos pop-out and they include links. Can you add them?

**Comment by 0xMuluh** [comment]
> One last request:
> 
> In the old page, the logos pop-out and they include links. Can you add them?

Humm, I don't get it. Did you mean the logo at the bottom? They are unchanged.  i have added Bioconductor and a link to it.

**Comment by TuomasBorman** [comment]
See the old page. If you put cursor on top of the logo, it gets colored and if you click the link, you get directed to external website.

It seems that this new one does not have that functionality?

**Comment by 0xMuluh** [comment]
it has the functionality.

**Comment by TuomasBorman** [comment]
Sorry, I believe I had the old version

**Review by TuomasBorman — APPROVED** [review]
Looks nice!

**Pull request merged**
